//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VergiNoDogrula.i18n {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VergiNoDogrula.i18n.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutTooltip {
            get {
                return ResourceManager.GetString("AboutTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Taxpayer.
        /// </summary>
        public static string AddTaxPayerDialogTitle {
            get {
                return ResourceManager.GetString("AddTaxPayerDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to add a new taxpayer.
        /// </summary>
        public static string AddTaxPayerTooltip {
            get {
                return ResourceManager.GetString("AddTaxPayerTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup created successfully: {0}.
        /// </summary>
        public static string BackupCreatedFormat {
            get {
                return ResourceManager.GetString("BackupCreatedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database backup could not be created..
        /// </summary>
        public static string BackupCreateFailed {
            get {
                return ResourceManager.GetString("BackupCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to backup the database.
        /// </summary>
        public static string BackupDatabaseTooltip {
            get {
                return ResourceManager.GetString("BackupDatabaseTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during backup: {0}.
        /// </summary>
        public static string BackupErrorFormat {
            get {
                return ResourceManager.GetString("BackupErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup failed..
        /// </summary>
        public static string BackupFailed {
            get {
                return ResourceManager.GetString("BackupFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup File: {0}.
        /// </summary>
        public static string BackupFileNameFormat {
            get {
                return ResourceManager.GetString("BackupFileNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Files.
        /// </summary>
        public static string BackupListDialogTitle {
            get {
                return ResourceManager.GetString("BackupListDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while loading backup files: {0}.
        /// </summary>
        public static string BackupLoadErrorFormat {
            get {
                return ResourceManager.GetString("BackupLoadErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear search box.
        /// </summary>
        public static string ClearSearchTooltip {
            get {
                return ResourceManager.GetString("ClearSearchTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseButton {
            get {
                return ResourceManager.GetString("CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string ConfirmationTitle {
            get {
                return ResourceManager.GetString("ConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy tax number.
        /// </summary>
        public static string CopyTaxNumberTooltip {
            get {
                return ResourceManager.GetString("CopyTaxNumberTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date.
        /// </summary>
        public static string CreatedDateHeader {
            get {
                return ResourceManager.GetString("CreatedDateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while loading data: {0}.
        /// </summary>
        public static string DataLoadErrorFormat {
            get {
                return ResourceManager.GetString("DataLoadErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected record?.
        /// </summary>
        public static string DeleteConfirmation {
            get {
                return ResourceManager.GetString("DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while deleting: {0}.
        /// </summary>
        public static string DeleteErrorFormat {
            get {
                return ResourceManager.GetString("DeleteErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to delete the selected taxpayer.
        /// </summary>
        public static string DeleteTaxPayerTooltip {
            get {
                return ResourceManager.GetString("DeleteTaxPayerTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This tax number already exists..
        /// </summary>
        public static string DuplicateTaxNumber {
            get {
                return ResourceManager.GetString("DuplicateTaxNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Tax Number already exists.
        /// </summary>
        public static string DuplicateTaxNumberError {
            get {
                return ResourceManager.GetString("DuplicateTaxNumberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        public static string FileNameHeader {
            get {
                return ResourceManager.GetString("FileNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open folder: {0}.
        /// </summary>
        public static string FolderOpenErrorFormat {
            get {
                return ResourceManager.GetString("FolderOpenErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Number and TCKN Validator.
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A newer backup file was found since the last backup operation!.
        /// </summary>
        public static string NewerBackupFound {
            get {
                return ResourceManager.GetString("NewerBackupFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No backup files found.
        /// </summary>
        public static string NoBackupFilesFound {
            get {
                return ResourceManager.GetString("NoBackupFilesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records found in the database..
        /// </summary>
        public static string NoRecordsInDatabase {
            get {
                return ResourceManager.GetString("NoRecordsInDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records yet.
        /// </summary>
        public static string NoRecordsYet {
            get {
                return ResourceManager.GetString("NoRecordsYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OkButton {
            get {
                return ResourceManager.GetString("OkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to open the backup folder.
        /// </summary>
        public static string OpenBackupFolderTooltip {
            get {
                return ResourceManager.GetString("OpenBackupFolderTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to open the database folder.
        /// </summary>
        public static string OpenDatabaseFolderTooltip {
            get {
                return ResourceManager.GetString("OpenDatabaseFolderTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record not found..
        /// </summary>
        public static string RecordNotFound {
            get {
                return ResourceManager.GetString("RecordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while saving: {0}.
        /// </summary>
        public static string SaveErrorFormat {
            get {
                return ResourceManager.GetString("SaveErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to save the selected taxpayer.
        /// </summary>
        public static string SaveTaxPayerTooltip {
            get {
                return ResourceManager.GetString("SaveTaxPayerTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search...
        /// </summary>
        public static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View backup files.
        /// </summary>
        public static string ShowBackupListTooltip {
            get {
                return ResourceManager.GetString("ShowBackupListTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string SizeHeader {
            get {
                return ResourceManager.GetString("SizeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Number.
        /// </summary>
        public static string TaxNumberHeader {
            get {
                return ResourceManager.GetString("TaxNumberHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Number:.
        /// </summary>
        public static string TaxNumberLabel {
            get {
                return ResourceManager.GetString("TaxNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax No:.
        /// </summary>
        public static string TaxNumberShortLabel {
            get {
                return ResourceManager.GetString("TaxNumberShortLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record deleted successfully..
        /// </summary>
        public static string TaxPayerDeletedSuccess {
            get {
                return ResourceManager.GetString("TaxPayerDeletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxpayer information saved successfully..
        /// </summary>
        public static string TaxPayerSavedSuccess {
            get {
                return ResourceManager.GetString("TaxPayerSavedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} taxpayer record(s) loaded successfully..
        /// </summary>
        public static string TaxPayersLoadedFormat {
            get {
                return ResourceManager.GetString("TaxPayersLoadedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string TitleHeader {
            get {
                return ResourceManager.GetString("TitleHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        public static string TitleLabel {
            get {
                return ResourceManager.GetString("TitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string WarningTitle {
            get {
                return ResourceManager.GetString("WarningTitle", resourceCulture);
            }
        }
    }
}
